### ISSUE TITLE
Counter part for Avoid purging Revisions #10678

### ISSUE THREAD

**Issue by disconnect821** [wagtail-nest/wagtail-ab-testing#53]
This is a counterpart for issue https://github.com/wagtail/wagtail/issues/10678 which changes the foreign key relation of `ABTest` to `PageRevision` from `models.CASCADE`  to  `models.PROTECT`

**Comment by Stormheg** [comment]
Hi @disconnect821, thanks for raising this as an issue first.

Changing the ForeignKey from `CASCASE` to `PROTECT` sounds fine to me. Be sure to base your work on my branch that has been updated to work with Wagtail 4.1+: https://github.com/Stormheg/wagtail-ab-testing/tree/support/wagtail42 The current `main` of this project only works with old versions of Wagtail and a lot has changed, making your change against the current

When you make this change, could you please also add a test that proves `ProtectedError` is raised when an attempting to delete a revision in use by a `AbTest` model. [You may find this test helpful](https://github.com/wagtail-nest/wagtail-ab-testing/pull/52/files#diff-e0c503255482487ae9bd3676b175e1cec395467885e06c1bc0d35e86323d546dR12-R23). it already does 90% of what you need to test. All you need to do is check `ProtectedError` is raised when deleting a revision.

Regarding the above reference to 'basing your work on my branch' I recommend you take the following steps:

1. Fork this repository and clone in to your computer
2. Add my fork as a git remote (assuming you use git cli): `$ git remote add Stormheg https://github.com/Stormheg/wagtail-ab-testing.git`
3. Fetch all remotes `$ git fetch --all`
4. Checkout my branch: `$ git checkout support/wagtail42`
5. Rename the branch to something more sensible for the change you are making: `$ git branch -m fix/mark-revision-relation-as-protected`
6. Make your changes and commit your changes!
7. Create a pull request. It will include all changes made on my branch, be sure to mention in the pull request description that your work is dependant on my PR: https://github.com/wagtail-nest/wagtail-ab-testing/pull/52. It is also good practice to reference the issue your PR is fixing, that would be this issue.

Thanks again for wanting to work on this! ❤️

**Comment by disconnect821** [comment]
Thanks @Stormheg, I'm on it.

**Comment by disconnect821** [comment]
@Stormheg  Can you provide me some tips for writing tests as I'm not very experienced with tests?

**Comment by Stormheg** [comment]
@salty-ivy running the tests is not that well documented in the readme, here is how I did it.

Assuming you are inside a [virtualenv](https://learnpython.com/blog/how-to-use-virtualenv-python/)
```sh
# Install wagtail-ab-testing in editable mode along with its testing dependencies
pip install -e ".[testing]"

# Run the tests
python testmanage.py test
```

**Comment by Stormheg** [comment]
@disconnect821 If you need some general information on how to write tests I recommend part 5 of the Django tutorial: https://docs.djangoproject.com/en/4.2/intro/tutorial05/.

salty-ivy provided you with an example on how to check if a specific type of exception is raised. Thank you Aman Pandey!

In my earlier comment I outlined what I would expect you to test. I hope this gives you enough guidance on what to do. It is up to you to research and gather the necessary knowledge to complete the goal of writing a test.

Writing tests is part of developing quality software. I hope you see this an opportunity to learn something new that will bring you further in your journey as a software developer.
