### ISSUE TITLE
RemovedInWagtail60Warning: UserPagePermissionsProxy.for_page() is deprecated

### ISSUE THREAD

**Issue by Stormheg** [wagtail-nest/wagtail-ab-testing#57]
The `UserPagePermissionProxy` class was deprecated in Wagtail 5.1 and will be removed in Wagtail 6: https://docs.wagtail.org/en/stable/releases/5.1.html#userpagepermissionsproxy-is-deprecated

It is used here: https://github.com/wagtail-nest/wagtail-ab-testing/blob/d04bd0032c4335a839c781851b12fe16037950de/wagtail_ab_testing/views.py#L206

We should consider backwards compatibility with older versions of Wagtail when fixing this.

**Comment by zerolab** [comment]
an example implementation: https://github.com/zerolab/wagtail-periodic-review/pull/13/commits/50b78a1c7e50f643d891d79e359afb65e6519e80
