### ISSUE TITLE
Support Wagtail 5.0's dark mode

### ISSUE THREAD

**Issue by Stormheg** [wagtail-nest/wagtail-ab-testing#62]
The pages added by this package should display properly in dark mode.

This is what is looks like now:

<img width="2105" alt="image" src="https://github.com/wagtail-nest/wagtail-ab-testing/assets/13856515/cc151ab8-77a0-4ad3-8678-d09d5d2dbc48">

It should have proper contrasting colors in dark mode.

**Comment by jhonatan-lopes** [comment]
Working on it.
